### ISSUE TITLE
Write failing with "invalid precision; valid precision units are ns, us, ms, and s"

### ISSUE THREAD

**Issue by Keksparade** [influxdata/influxdb-client-ruby#107]
Hi, 

this is probably more a screaming for help than a bug report, but I cannot get the write API to work correctly. Can you please point me to the right direction?

I'm trying to write data to InfluxDB 2.x but I'm getting an error regarding precision all the time: "invalid precision; valid precision units are ns, us, ms, and s". After trying various things I still don't get where the issue is and where I need to set or manipulate precision in order to get it working. Any help would be appreciated!

__Steps to reproduce:__
I'm trying to write some data to InfluxDB 2.x using the following code snippet:
```  influxdb = InfluxDB2::Client.new(
    'http://influxdbhost:8086', 
  'my_token_here',
    bucket: 'my_bucket',
    org: 'my_org',
	precision: 'InfluxDB2::WritePrecision::NANOSECOND',
	use_ssl: false
  )

  data = {
    name: 'statistics', 
    fields: {
      warnings: count(lines,'W'),
      neutral: count(lines,'N'),
      errors: count(lines,'E'),
      counter: counter
    },
    tags: { source: "mystuff" }
  }

  puts data

  write_api = influxdb.create_write_api
  write_api.write(data: data)
  influxdb.close!
```

The output of data is `{:name=>"statistics", :fields=>{:warnings=>16, :neutral=>63, :errors=>0, :counter=>"2156"}, :tags=>{:source=>"mystuff"}}` which looks reasonable.

I already tried various stuff like not setting the precision in the client or using seconds instead of nanoseconds. I also added a "time" entry in the data in parallel to name, fields and tag and used `Time.now.to_i` but that didn't work either. 

__Expected behavior:__
No errors, Data available in InfluxDB

__Actual behavior:__
No data available. Error is returned with "invalid precision; valid precision units are ns, us, ms, and s"

__Specifications:__
 - Client Version: influxdb-client (2.6.0)
 - InfluxDB Version: InfluxDB v2.3.0+SNAPSHOT.090f681737
 - Platform: Ubuntu 20.04.4 LTS

**Comment by bednar** [comment]
Hi @Keksparade,

thanks for using our client.

> I'm trying to write data to InfluxDB 2.x but I'm getting an error regarding precision all the time: "invalid precision; valid precision units are ns, us, ms, and s". After trying various things I still don't get where the issue is and where I need to set or manipulate precision in order to get it working. Any help would be appreciated!

You have to set the precision without apostrhorfe or just a string. 

```ruby
require 'influxdb-client'

client = InfluxDB2::Client.new('http://localhost:8086',
                               'my-token',
                               bucket: 'my-bucket',
                               org: 'my-org',
                               precision: InfluxDB2::WritePrecision::NANOSECOND,
                               use_ssl: false
                              )

data = 'h2o,level=a value=5'

puts data

write_api = client.create_write_api
write_api.write(data: data)
client.close!
```
