### ISSUE TITLE
Support for Task CRUD apis

### ISSUE THREAD

**Issue by prevosti** [influxdata/influxdb-client-ruby#125]
__Proposal:__
Implement the Tasks apis listed in the documentation: https://docs.influxdata.com/influxdb/v2.5/api/#tag/Tasks

**Comment by bednar** [comment]
Hi @prevosti,

thanks for using our client. 

We will take a look.

Regards

**Comment by prevosti** [comment]
That's great, thank you @bednar !

**Comment by prevosti** [comment]
@bednar I tried the code and it works great, would it be possible to cut the 2.9.0 release soon?

**Comment by bednar** [comment]
We will release the client by the end of the month. Meanwhile you can use nightly build - https://rubygems.org/gems/influxdb-client-apis/versions/2.9.0.pre.6399

**Comment by prevosti** [comment]
Sounds good, thank you!
