### ISSUE TITLE
An influxdb v1.8 HTTP error response message is not correctly transfered to InfluxError message

### ISSUE THREAD

**Issue by alxndrdude** [influxdata/influxdb-client-ruby#133]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. setup a dummy InfluxDB v1.8 database
2. write a measurement, which fails e.g. with HTTP status code 400
3. inspect/log the raised `InfluxDB2::InfluxError`

__Expected behavior:__
The `InfluxDB2::InfluxError` contains the "reason of failure" as `message`.

__Actual behavior:__
The `InfluxDB2::InfluxError` has an empty `message` (`code` is present).

This makes it very hard to debug failed writes w.r.t a the InfluxDB v1.8 `api/v2` interface.

__Specifications:__
 - Client Version: v3.0.0
 - InfluxDB Version: v1.8.10 (in docker)
 - Platform: Linux (ubuntu)

__Detailed example:__

1. setup a database ` dummy_db`
2. Write a measurement with type `integer`: 
```
curl -X POST "localhost:8086/api/v2/write?bucket=dummy_db/autogen&precision=us"   -H 'Authorization: Token username:password'   --data-raw "DummySample,id=1 value=52 1701767568149969"
```
3.  Write a measurement with type `integer`: 
```
curl -X POST "localhost:8086/api/v2/write?bucket=dummy_db/autogen&precision=us"   -H 'Authorization: Token username:password'   --data-raw "DummySample,id=1 value=52i 1701767569149969"

-> {"error":"partial write: field type conflict: input field \"value\" on measurement \"DummySample\" is type integer, already exists as type float dropped=1"}
```

4. Perform the same step via InfluxDB2::Client
```
c = InfluxDB2::Client.new(...)
writer = c..create_write_api(...)
point = InfluxDB2::Point.new(name: "DummySample'', time: Time.current, fields: { value: 54 }, tags: { id: 1 }, precision: 'us'
writer.write(data: point)

# -> raises InfluxDB2::InfluxError without message
```

**Comment by bednar** [comment]
Hi @alxndrdude,

thanks for using our client.

Is this something you would be willing to help with? All PR is welcome and we will be happy to review your submission.

Regards

**Comment by alxndrdude** [comment]
Hi @bednar ,
Actually a fix should not be too complicated.

A first suggestion would be:
``` diff
diff --git a/lib/influxdb2/client/influx_error.rb b/lib/influxdb2/client/influx_error.rb
index aad02a0..dde3873 100644
--- a/lib/influxdb2/client/influx_error.rb
+++ b/lib/influxdb2/client/influx_error.rb
@@ -32,7 +32,7 @@ module InfluxDB2
 
     def self.from_response(response)
       json = JSON.parse(response.body)
-      obj = new(message: json['message'] || '', code: response.code, reference: json['code'] || '',
+      obj = new(message: json['message'] || json['error'] || '', code: response.code, reference: json['code'] || '',
                 retry_after: response['Retry-After'] || '')
       obj
     rescue JSON::ParserError
```

to be compatible with the influxdb v1.8 error response.

Should I fork and make a PR from there, or push some `fix-issue-133-...` branch?

Thanks

**Comment by bednar** [comment]
> Should I fork and make a PR from there, or push some fix-issue-133-... branch?

Yes, please go ahead and create a fork, then make a PR from there. I'll be happy to review it.
