### ISSUE TITLE
Add QueryAPI

### ISSUE THREAD

**Issue by bednar** [influxdata/influxdb-client-ruby#14]
- [ ] check v1 client: https://github.com/influxdata/influxdb-ruby#querying
- [ ] add light way `query_api` (synchronous) that will follow structure in our others client
- [ ] create `FluxRecord`, `FluxTable`, ... as is in other clients

**Comment by giovannelli** [comment]
Hi @bednar,
when do you think the query api will be available? 
Thank you

**Comment by bednar** [comment]
Hi @giovannelli, 

Today we start working on it so i suppose that a first version will be available in late of next week.

Regards
