### ISSUE TITLE
Query method: read_body called twice 

### ISSUE THREAD

**Issue by giovannelli** [influxdata/influxdb-client-ruby#16]
``` console
irb(main):039:0> result = query_api.query(query: 'from(bucket:"' + bucket + '") |> range(start: 1970-01-01T00:00:00.000000001Z) |> last()')
Traceback (most recent call last):
        4: from bin/console:14:in `<main>'
        3: from (irb):39
        2: from /Users/giovannelli/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/bundler/gems/influxdb-client-ruby-3c32bcbe6afb/lib/influxdb2/client/query_api.rb:60:in `query'
        1: from /Users/giovannelli/.rbenv/versions/2.6.5/lib/ruby/2.6.0/net/http/response.rb:198:in `read_body'
IOError (Net::HTTPOK#read_body called twice)
```

The issue seems to be here:

``` ruby
# lib/influxdb2/client/query_api.rb:60
...
      response.read_body do |chunk|
        parser.parse(chunk)
      end
...
```
The following patch works, but probably you prefer to keep reading responses in chunk.

``` ruby
parser.parse(response.body)
```

Are you planning to add a query DSL instead of using the raw query? And are you planning to format the response some how? Just to avoid doing the work twice.

Thank you,
Duccio

**Comment by russorat** [comment]
@giovannelli thanks for the issue. We will take a look at that specific bug.

> Are you planning to add a query DSL instead of using the raw query? And are you planning to format the response some how?

we definitely want to add those in the future. this lib is brand new so we are just getting started. We'd love to gather input from the community on how to make this lib as easy to use as possible.

**Comment by bednar** [comment]
Hi @giovannelli,

We currently works on `query_api`. There will be different options how to use the `query_api`:

1. `query_api.query_raw` - Synchronously executes the Flux query and return result as unprocessed `String`
1. `query_api.query` - Synchronously executes the Flux query and return result as a `Array` of [FluxTables](https://github.com/influxdata/influxdb-client-ruby/blob/3c32bcbe6afba0e83ef1e0964c57032cfe932454/lib/influxdb2/client/flux_table.rb#L24)
1. `query_api.query_stream` - Synchronously executes the Flux query and return stream of [FluxRecord](https://github.com/influxdata/influxdb-client-ruby/blob/3c32bcbe6afba0e83ef1e0964c57032cfe932454/lib/influxdb2/client/flux_table.rb#L34)

This week we want to finish first two options - see https://github.com/influxdata/influxdb-client-ruby/pull/15

Regards
