### ISSUE TITLE
Delete predicate

### ISSUE THREAD

**Issue by giovannelli** [influxdata/influxdb-client-ruby#20]
Hi there,
sorry to bother you again, but are you planning to add the delete endpoint to the gem?
Could you share the ETA for the first gem release?

Thank you,
Duccio

**Comment by bednar** [comment]
Hi @giovannelli 

version 1.1.0 will be released this Friday. 

The `delete endpoint` is a good idea we will start works on it after #19 .

Regards

**Comment by giovannelli** [comment]
@bednar thank you.

**Comment by bednar** [comment]
Hi @giovannelli,

The issue is fixed in [1.2.0 milestone](https://github.com/influxdata/influxdb-client-ruby/milestone/3). 

If you would like to use a preview version use this gem: [ influxdb-client (1.2.0.pre.529) ](https://rubygems.org/gems/influxdb-client/versions/1.2.0.pre.529)

Regards
