### ISSUE TITLE
InfluxDB2 not Initialized vie GEMFILE

### ISSUE THREAD

**Issue by minardimedia** [influxdata/influxdb-client-ruby#31]
I add the gem to my GEMFILE in a Rails project

`gem 'influxdb-client`

but the module doesn't get initialized.

`NameError: uninitialized constant InfluxDB2`

**Comment by bednar** [comment]
Hi @minardimedia,

thanks for using our library.

Did you install dependencies via `bundle install` or did you load client via `require 'influxdb2/client'`?

Regards

**Comment by minardimedia** [comment]
Hi bednar,

I use `bundle install`

it shows already in my Gemfile.lock

**Comment by bednar** [comment]
I prepared simple Rails project with `InfluxDB2` client: https://github.com/bednar/influxdb-client-ruby-demo:

![image](https://user-images.githubusercontent.com/455137/76504169-782ea580-6447-11ea-9e9c-0ac419f9d114.png)

Here is a controller with client: 

https://github.com/bednar/influxdb-client-ruby-demo/blob/1c7d1f5695c0076e8d5d0fe2291515589de90f70/app/models/pages_controller.rb#L6

You could test it by:

1. `git clone git@github.com:bednar/influxdb-client-ruby-demo.git`
1. `cd influxdb-client-ruby-demo`
1. `rails server`
1. and open [http://localhost:3000/pages/influxdb](http://localhost:3000/pages/influxdb)

**Comment by minardimedia** [comment]
Thank you very much!

I will clone the project and check it out
