### ISSUE TITLE
Why is there a new client?

### ISSUE THREAD

**Issue by ChrisBr** [influxdata/influxdb-client-ruby#39]
I was wondering why it was necessary to create a new gem for 2.0 and not adapting the already well used https://github.com/influxdata/influxdb-ruby (which happens to be also in the same organization so permissions shouldn't be a problem?).

This makes it very confusing for the community which gem to use. Additionally this brings us as maintainers of https://github.com/influxdata/influxdb-rails in a difficult position? How are we supposed to support this?

cc @hennevogel

**Comment by AxelTheGerman** [comment]
I'm confused too, just started looking at InfluxDB as alternative to TimescaleDB but which gem do I start with now?

Would be great if both repos could have a note what the difference is between the two and which (or how) to choose.

Looks like this one might cause the other one to be faded out one day? https://github.com/influxdata/influxdb-client-ruby/issues/8#issuecomment-571721491

**Comment by timhallinflux** [comment]
There is a completely different API for InfluxDB 2.0.  So, all of the client libraries have been overhauled to support this.  What has also been done is that we backported the 2.0 API to the 1.8 version of InfluxDB.  Hence, you should be able to use the new client libraries with 1.x starting with the 1.8 release.  This provides you with forward compatibility.

We can certainly update the README in the 1.x client to highlight that the new client exists and that is the recommended path forward.

**Comment by kaspergrubbe** [comment]
Not doubting your rewrite here, even though I do find it puzzling why it was needed, but why couldn't this new version be a new version of the old gem instead of creating a completely new one?
