### ISSUE TITLE
How to delete time series in InfluxDB v1.8

### ISSUE THREAD

**Issue by DaisukeKogasaki** [influxdata/influxdb-client-ruby#40]
Hello.
I'm using this gem in InfluxDB v1.8.
This version does not support the '/api/v2/delete' endpoint, so you can't delete the time series.
I can delete the time series by using the '/query' endpoint without using the gem, but can't I delete the time series using '/api/v2/query' etc.?
Sorry if I'm asking in the wrong place.
Best regards.

**Comment by bednar** [comment]
Hi @DaisukeKogasaki,

Unfortunately the endpoint `/api/v2/query` doesn't supports deleting time series.

Regards

**Comment by DaisukeKogasaki** [comment]
Hello, @bednar,
Thanks for the quick answer!
So, we'll keep the current implementation.
I will change to a gem-based implementation when I upgrade to InfluxDB v2.0.
Thank you!

**Comment by bednar** [comment]
You are welcome
