### ISSUE TITLE
Ruby 2.2 does not support `.positive?`

### ISSUE THREAD

**Issue by niborg** [influxdata/influxdb-client-ruby#43]
I'm on a stack using Ruby 2.2.1. Batch processing fails due to [this line](https://github.com/influxdata/influxdb-client-ruby/blob/a305f0207c0c5b73b3b681857c1b78893ada7f59/lib/influxdb2/client/worker.rb#L102) in the `Worker` class.

I don't think Ruby added `.positive?` or `.negative?` methods until Ruby 2.3.

**Comment by bednar** [comment]
Hi @niborg,

The issue is fixed in [1.6.0 milestone](https://github.com/influxdata/influxdb-client-ruby/milestone/7). 

If you would like to use a preview version use our nightly build: [influxdb-client 1.6.0.pre.963](https://rubygems.org/gems/influxdb-client/versions/1.6.0.pre.963).

Regards
