### ISSUE TITLE
Exceptions in the Influx write worker will bubble up

### ISSUE THREAD

**Issue by webdestroya** [influxdata/influxdb-client-ruby#51]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. have a process that emits metrics
2. cause the metrics to fail to report (unplug network/block traffic/etc)
3. your entire process crashes out

__Expected behavior:__
I expect that my metrics reporter background thread does not cause my job system to fail. If I have thousands of jobs, I'd much rather have some missing stats vs crashing out the process and having to restart

__Actual behavior:__
Describe What actually happened.

`Thread.abort_on_exception = true` setting in the worker.rb class causes exceptions to bubble up to the calling thread, which will act as a regular exception, and breaks logic flow.

I understand that this is desired in some cases, but then it should be an option, AND it should be within the threads that Influx starts (using `Thread.current.abort_on_exception = true`). Right now it sets it for the entire thread. Metrics should be a best-effort, if it cant send a metric, then log a message or something but please don't throw an exception that halts everything.

__Specifications:__
 - Client Version: 1.7.0
 - InfluxDB Version: 2.0
 - Platform: mac / linux / ruby 2.7.1

**Comment by bednar** [comment]
Hi @webdestroya,

thanks for report an issue. We will change the `abort_on_exception` to threads that `worker.rb` starts. 

The client is able to handle network exceptions by a retry strategy - see details: https://github.com/influxdata/influxdb-client-ruby#batching. You could increase `max_retries` and `max_retry_delay` to be more resilient.

If the default retry strategy isn't good enough we could prepare a possibility of custom implementation.

Regards

**Comment by webdestroya** [comment]
Is it possible to make this configurable?

**Comment by bednar** [comment]
@webdestroya #53 introduces configurable option `batch_abort_on_exception` - with default value to `false`. 

Could you add a review to #53?
