### ISSUE TITLE
Write api with timestamp not written into db

### ISSUE THREAD

**Issue by adriany3m** [influxdata/influxdb-client-ruby#57]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

I am following along with the provided code samples.

```
client = InfluxDB2::Client.new('https://localhost:8086', 'my-token',
                              bucket: 'my-bucket',
                              org: 'my-org',
                              precision: InfluxDB2::WritePrecision::NANOSECOND)

client.create_write_api.write(data: [
  { name: 'cpu', tags: { host: 'server_nl', region: 'us' }, fields: { internal: 5, external: 6 }, time: 1_422_568_543_702_900_257 }, 
  { name: 'gpu', fields: { value: 0.9999 } }
])
```

However, the point where the timestamp is included (CPU) is not written into the db. Removing the timestamp seems to fix the issue. 

I am still very new to influxdb so my apologies if i have overlooked anything. 

__Expected behavior:__

Both measurement CPU and GPU should be written into the db. 

__Actual behavior:__

Only GPU is written into the db. 

__Specifications:__
 - Client Version: 1.9
 - InfluxDB Version: 2.0
 - Platform:

**Comment by bednar** [comment]
Hi @adriany3m,

thanks for using our client.

Your time is set to 1_422_568_543_702_900_257 which is **GMT: Thursday, January 29, 2015 9:55:43.702 PM**. 

Did you set correct range in UI?

![image](https://user-images.githubusercontent.com/455137/99937138-3b040c80-2d65-11eb-885b-da53dba4f5c2.png)

Here is my test code:

```ruby
require 'influxdb-client'

bucket = 'my-bucket'
org = 'my-org'

client = InfluxDB2::Client.new('http://localhost:8086', 'my-token',
                               bucket: bucket,
                               org: org,
                               use_ssl: false,
                               precision: InfluxDB2::WritePrecision::NANOSECOND)

puts '*** Write Points ***'

client.create_write_api.write(data: [
    {name: 'cpu', tags: {host: 'server_nl', region: 'us'}, fields: {internal: 5, external: 6}, time: 1_422_568_543_702_900_257},
    {name: 'gpu', fields: {value: 0.9999}}
])

puts '*** Query Points ***'

query_api = client.create_query_api
tables = query_api.query(query: "from(bucket: \"#{bucket}\") |> range(start: 0)")
tables.each do |_, table|
  table.records.each { |record| puts "#{record.time} #{record.measurement}: #{record.field} #{record.value}" }
end

client.close!
```

Regards

**Comment by adriany3m** [comment]
Thank you for the prompt response. Indeed, the precision type I provided does not match the timestamp.
