### ISSUE TITLE
rfc3339 time conversion removing fractional seconds from query results

### ISSUE THREAD

**Issue by dslik** [influxdata/influxdb-client-ruby#60]
When I perform a query against InfluxDB 2 in the web console, I see timestamps showing up with sub-second resolution, as expected.

However, when using the ruby client to perform the same query, the results only include strings with second-granular timestamps.

I tracked this down to the use of to_datetime.rfc3339 in flux_csv_parser, specifically:

https://github.com/influxdata/influxdb-client-ruby/blob/bca6f996ab48537d77aad084984a90892fa40776/lib/influxdb2/client/flux_csv_parser.rb#L247

When I instrument this, I see the correct timestamps being returned from InfluxDB, but once converted, the sub-second time information is lost, e.g.:

    Returned from Influx 2 Server : 2020-12-02T04:31:24.340651Z
    After influxdb time conversion: 2020-12-02T04:31:24+00:00
    Returned from Influx 2 Server : 2020-12-02T04:31:12.782593Z
    After influxdb time conversion: 2020-12-02T04:31:12+00:00

Changing:

    Time.parse(str_val).to_datetime.rfc3339

to

    Time.parse(str_val).to_datetime.rfc3339(9)

returns the expected sub-second resolution.

**Comment by bednar** [comment]
@dslik thanks for an issue, I will take a look

**Comment by bednar** [comment]
Hi @dslik,

the issue is fixed in a Milestone 1.10.0. 

You could use dev version [1.10.0.pre.1440](https://rubygems.org/gems/influxdb-client/versions/1.10.0.pre.1440)

Regards
