### ISSUE TITLE
User Management?

### ISSUE THREAD

**Issue by andyl** [influxdata/influxdb-client-ruby#64]
It looks as if the ruby-client functionality is focused on data read/writes.   Can `influxdb-client-ruby` be used to manage users, organizations, members, auth tokens?

**Comment by bednar** [comment]
Hi @andyl,

thanks for using our client.

Currently not, but we can do something in upcoming release.

Could you describe your usecase?

Regards

**Comment by andyl** [comment]
Hey @bednar thanks for answering my question.  My use case is to automate the setup of an InfluxDB instance with scripts.  No worries I'll drop back to the HTTP api.
