### ISSUE TITLE
Influx Cloud does not accept point with timestamp

### ISSUE THREAD

**Issue by ChrisBr** [influxdata/influxdb-client-ruby#68]
Good afternoon 👋 

We're porting the influxdb-rails gem to work with the influxdb-client-ruby gem. 

I created a new account in InfluxDB and it seems it doesn't accept values when I include a timestamp

This does not work

```
POST https://us-west-2-1.aws.cloud2.influxdata.com/api/v2/write?bucket=bla&org=foo@gmail.com&precision=ns with body 'block_instrumentation,hook=block_instrumentation,location=raw,name=name,server=hostname value=43i 151479720000000000
```

The response is `HTTPNoContent` though.

If I remove the timestamp it works though.

```
POST https://us-west-2-1.aws.cloud2.influxdata.com/api/v2/write?bucket=bla&org=foo@gmail.com&precision=ns with body 'block_instrumentation,hook=block_instrumentation,location=raw,name=name,server=hostname value=43i
```

We create the client with

```ruby
  InfluxDB::Rails.client = InfluxDB2::Client.new(
      'https://us-west-2-1.aws.cloud2.influxdata.com',
      token,
      precision: InfluxDB2::WritePrecision::NANOSECOND,
      bucket:    bucket,
      org:       org
    )
```

Version is influxdb-client (1.11.0)

Any thoughts how to debug this?

**Comment by bednar** [comment]
Hi @ChrisBr,

The `HTTPNoContent` is successful response from InfluxDB API:

![image](https://user-images.githubusercontent.com/455137/107918429-f0f88480-6f69-11eb-95d9-c74f228fe60e.png)
https://docs.influxdata.com/influxdb/v2.0/api/#tag/Write

I just tried it with Cloud and OSS by following piece of code:

```ruby
require 'influxdb-client'

url = 'https://us-west-2-1.aws.cloud2.influxdata.com'
token = 'my-token'
bucket = 'my-bucket'
org = 'my-org'

client = InfluxDB2::Client.new(url,
                               token,
                               bucket: bucket,
                               org: org,
                               use_ssl: true,
                               precision: InfluxDB2::WritePrecision::NANOSECOND)

puts '*** Write Point ***'

write_api = client.create_write_api
response = write_api.write(data: 'block_instrumentation,hook=block_instrumentation,location=raw,name=name,server=hostname value=43i 151479720000000000')

puts "HTTP code: #{response.code}, HTTP response: #{response}"

client.close!
```

and everything works correctly.

Regards

**Comment by ChrisBr** [comment]
@bednar thanks for the help. I investigated this again and there was a default deletion policy of 30 days on the bucket and the test metrics tried to write were older than 30 days. Everything works as expected, thanks!
