### ISSUE TITLE
Use oj gem for dumping json

### ISSUE THREAD

**Issue by nicovak** [influxdata/influxdb-client-ruby#72]
__Proposal:__
Use `oj` gem for betters perf [oj](https://github.com/ohler55/oj)

__Current behavior:__

Actually it uses `JSON.parse`, example in health API

```
JSON.parse("[#{body}]", symbolize_names: true)[0]
```

__Desired behavior:__

## JSON to Ruby Hash

```ruby
# REPLACE
JSON.parse("[#{body}]", symbolize_names: true)[0]

# BY
Oj.load("[#{body}]", symbol_keys: true)[0]
```

## Hash to JSON
```ruby
Oj.dump(data, mode: :compact)
```

__Use case:__
Performances

**Comment by bednar** [comment]
@vslee, thanks for the suggestion 👍 Is this something you might be willing to help with?

**Comment by nicovak** [comment]
@bednar of course

**Comment by bednar** [comment]
Awesome, thanks 👍

**Comment by Esity** [comment]
@nicovak  @bednar  

We should reconsider this. If you add an OJ dependency then this gem won't be usable by by jruby. 
An alternative is to use multi_json and let it sort it out based on other gems installed.

**Comment by Esity** [comment]
@russorat Not sure who technically manages/owns these repos but my previous comment should be a reason to close this change and I do not have access to do so

**Comment by russorat** [comment]
Closing this request. See @Esity 's comment.

**Comment by bednar** [comment]
@Esity thanks for your suggestion. I also add a new build with `jruby` into our CI pipeline - #78
