### ISSUE TITLE
Development status 

### ISSUE THREAD

**Issue by giovannelli** [influxdata/influxdb-client-ruby#8]
Hi @bednar,
I see you are actively working on the api v2 version of the gem and on my side I'm actively testing it :)
Could you share with us the dev status and an ETA for a production ready release?
Could you also start testing against ruby 2.7.0, I've seen that apart from a webmock gem warning, all tests pass!

Thank you for your work.

Best,
Duccio

**Comment by bednar** [comment]
Hi @giovannelli,

Just for clarification... we develop `influxdb-client-ruby` as a base for the [InfluxDB 2 Fluentd plugin](https://github.com/bonitoo-io/influxdb-plugin-fluent). 

The version [1.0.0.beta](https://github.com/bonitoo-io/influxdb-client-ruby/milestone/1) covers our requirements for fluentd plugin and will be released at the end of next week.

Currently it's feature complete and I only fix bugs. So you are welcome to any PR and I will merge it immediately ;).

I will add testing against ruby 2.7.0 tomorrow.

Regards

**Comment by giovannelli** [comment]
Hi @bednar, thank you!
Are you planning to add a query layer as in the previous gem https://github.com/influxdata/influxdb-ruby#querying? And what about the async writes?

Best,
Duccio

**Comment by bednar** [comment]
Hi @giovannelli,

Short answer: Yes.

We would like to add same functionality as is in: [influxdb-client-python](https://github.com/influxdata/influxdb-client-python), [influxdb-client-python](https://github.com/influxdata/influxdb-client-python), [influxdb-client-csharp](https://github.com/influxdata/influxdb-client-csharp), [influxdb-client-js](https://github.com/bonitoo-io/influxdb-client-js):

1. Async writes
1. Batch writes
1. QueryAPI
1. Light-way management API

and any PR is welcome ;)

Regards
