### ISSUE TITLE
Create Bucket with an SSL client

### ISSUE THREAD

**Issue by Galactic21** [influxdata/influxdb-client-ruby#80]
Good afternoon, I am using your API to automatically implement influxdb within instances from CHEF.  I already have your libraries installed and the scripts you put in the examples folder, namely "create_new_bucket.rb" are working correctly.  However, I already tried to implement these scripts with an ssl client and the chef returns this error to me:

`I, [2021-05-04T15:23:34.931515 #15072]  INFO -- pritunl-ubuntu-2004: /opt/chef/embedded/lib/ruby/gems/3.0.0/gems/ethon-0.14.0/lib/ethon/easy/operations.rb:44: [BUG] Segmentation fault at 0x00007f653fffde00
I, [2021-05-04T15:23:34.931846 #15072]  INFO -- pritunl-ubuntu-2004: ruby 3.0.1p64 (2021-04-05 revision 0fb782ee38) [x86_64-linux]
I, [2021-05-04T15:23:34.932011 #15072]  INFO -- pritunl-ubuntu-2004: 
I, [2021-05-04T15:23:34.932126 #15072]  INFO -- pritunl-ubuntu-2004: -- Control frame information -----------------------------------------------
I, [2021-05-04T15:23:34.932626 #15072]  INFO -- pritunl-ubuntu-2004: c:0047 p:---- s:0255 e:000254 CFUNC  :easy_perform
I, [2021-05-04T15:23:34.933707 #15072]  INFO -- pritunl-ubuntu-2004: c:0046 p:0014 s:0250 e:000249 METHOD /opt/chef/embedded/lib/ruby/gems/3.0.0/gems/ethon-0.14.0/lib/ethon/easy/operations.rb:44
I, [2021-05-04T15:23:34.934244 #15072]  INFO -- pritunl-ubuntu-2004: c:0045 p:0020 s:0246 e:000245 METHOD /opt/chef/embedded/lib/ruby/gems/3.0.0/gems/typhoeus-1.4.0/lib/typhoeus/request/operations.rb:16
I, [2021-05-04T15:23:34.934809 #15072]  INFO -- pritunl-ubuntu-2004: c:0044 p:0025 s:0241 e:000240 METHOD /opt/chef/embedded/lib/ruby/gems/3.0.0/gems/typhoeus-1.4.0/lib/typhoeus/request/cacheable.rb:18
I, [2021-05-04T15:23:34.935381 #15072]  INFO -- pritunl-ubuntu-2004: c:0043 p:0033 s:0236 e:000235 METHOD /opt/chef/embedded/lib/ruby/gems/3.0.0/gems/typhoeus-1.4.0/lib/typhoeus/request/block_connection.rb:31
I, [2021-05-04T15:23:34.936032 #15072]  INFO -- pritunl-ubuntu-2004: c:0042 p:0041 s:0232 e:000231 METHOD /opt/chef/embedded/lib/ruby/gems/3.0.0/gems/typhoeus-1.4.0/lib/typhoeus/request/stubbable.rb:25
I, [2021-05-04T15:23:34.936698 #15072]  INFO -- pritunl-ubuntu-2004: c:0041 p:0020 s:0227 e:000226 METHOD /opt/chef/embedded/lib/ruby/gems/3.0.0/gems/typhoeus-1.4.0/lib/typhoeus/request/before.rb:26
I, [2021-05-04T15:23:34.937082 #15072]  INFO -- pritunl-ubuntu-2004: c:0040 p:0019 s:0223 e:000222 METHOD /opt/chef/embedded/lib/ruby/gems/3.0.0/gems/influxdb-client-apis-1.14.0/lib/influxdb2/apis/generated/api_client.rb:51
I, [2021-05-04T15:23:34.937145 #15072]  INFO -- pritunl-ubuntu-2004: c:0039 p:0236 s:0213 e:000212 METHOD /opt/chef/embedded/lib/ruby/gems/3.0.0/gems/influxdb-client-apis-1.14.0/lib/influxdb2/apis/generated/api/buckets_api.rb:838
I, [2021-05-04T15:23:34.937192 #15072]  INFO -- pritunl-ubuntu-2004: c:0038 p:0011 s:0196 e:000195 METHOD /opt/chef/embedded/lib/ruby/gems/3.0.0/gems/influxdb-client-apis-1.14.0/lib/influxdb2/apis/generated/api/buckets_api.rb:785
I, [2021-05-04T15:23:34.937214 #15072]  INFO -- pritunl-ubuntu-2004: c:0037 p:0251 s:0187 e:000186 BLOCK  /tmp/kitchen/cache/cookbooks/ms_influxdb/resources/bucket.rb:35 [FINISH]
I, [2021-05-04T15:23:34.937381 #15072]  INFO -- pritunl-ubuntu-2004: c:0036 p:0004 s:0176 e:000175 BLOCK  (eval):2 [FINISH]`

I would like to know if there is any way to implement this with SSL or not yet implemented in the library itself ?!
Cheers.

**Comment by bednar** [comment]
Hi @Galactic21,

thanks for using our client.

> I would like to know if there is any way to implement this with SSL or not yet implemented in the library itself ?!
> Cheers.

You can turn the SSL by configuration. See docs - https://github.com/influxdata/influxdb-client-ruby#client-options. Something like could works:

```ruby
url = 'https://us-west-2-1.aws.cloud2.influxdata.com'
bucket = 'my-bucket'
org = 'my-org'
token = 'my-token'

client = InfluxDB2::Client.new(url,
                               token,
                               bucket: bucket,
                               org: org,
                               use_ssl: true,
                               precision: InfluxDB2::WritePrecision::NANOSECOND)
```

Regards

**Comment by Galactic21** [comment]
I had already tried it that way but to no avail. I now ran the test again and still have the same problem ..

The code is:

`resource_name :influxdb2_bucket
provides :influxdb2_bucket

unified_mode true

action :create do
  require 'influxdb-client'
  require 'influxdb-client-apis'

  url = 'https://influxdb.in.anbstuff.net:8086'
  bucket = 'pritunl'
  org = 'mailspike'
  token = '36kHw3S2AG_XeiQA8jO90XHyxLA6xAwj4MDTUqPY_gSUTjAyb3wsnNUYvuFVINyKUKTazg0ICsX9adpN8smbtg=='

  client = InfluxDB2::Client.new(url,
                               token,
                               bucket: bucket,
                               org: org,
                               use_ssl: true,
                               precision: InfluxDB2::WritePrecision::NANOSECOND)

  puts ("Client: #{client}")
  api = InfluxDB2::API::Client.new(client)
  puts ("API: #{api}")


  #
  # Create new Bucket
  #
  retention_rule = InfluxDB2::API::RetentionRule.new(type: 'expire', every_seconds: 3600)

  bucket_name = 'test10'
  orgid = 'd555c3d30a74cde4'

  request = InfluxDB2::API::PostBucketRequest.new(org_id: orgid,
                                                name: bucket_name,
                                                retention_rules: [retention_rule])

                                              
  puts ("Retention Rule: #{retention_rule}")
  puts ("Request: #{request}")

  bucket = api.create_buckets_api
            .post_buckets(request)

  puts ("Bucket: #{bucket}")     

  #
  # Create Permission to read/write from Bucket
  #
  resource = InfluxDB2::API::Resource.new(type: 'buckets',
                                        id: bucket.id,
                                        org_id: orgid)
  authorization = InfluxDB2::API::Authorization.new(description: "Authorization to read/write bucket: #{bucket.name}",
                                                  org_id: orgid,
                                                  permissions: [
                                                    InfluxDB2::API::Permission.new(action: 'read', resource: resource),
                                                    InfluxDB2::API::Permission.new(action: 'write', resource: resource)
                                                  ])
  result = api.create_authorizations_api
            .post_authorizations(authorization)

  print("The token: '#{result.token}' is authorized to read/write from/to bucket: '#{bucket.name}'.")


  # Find my organization
  organization = api.create_organizations_api
                  .get_orgs
                  .orgs
                  .select { |it| it.name == 'mailspike' }
                  .first
  
  puts ("Organization: #{organization}")
  puts ("Organization ID: #{organization.id}")

  buckets = api.create_buckets_api.get_buckets.org_id
                  
  puts ("Buckets: #{buckets}")
                  
  client.close!

end`

**Comment by Galactic21** [comment]
I had already tried it that way but to no avail. I now ran the test again and still have the same problem ..

![image](https://user-images.githubusercontent.com/32776046/117166065-f376b780-adbd-11eb-91f2-c1ef791dec78.png)

**Comment by bednar** [comment]
I don't see any SSL related error in your log 😢 ... 

Do you have detail log? Do you use self signed certificate?

Please try to following code to check your connection:

```ruby
uri = URI.parse(url)

http = Net::HTTP.new(uri.host, uri.port)
http.use_ssl = true

http.start do
  http.request_head('/health') do |res|
    puts res.each_header.to_h
  end
end
```

**Comment by Galactic21** [comment]
I discovered that the problem is in the interaction of the chef's environment with the library that your API uses, the Typhoeus. So I assume that unfortunately you cannot help me...

**Comment by bednar** [comment]
Which version of `Typhoeus` chef's environment requires?

**Comment by Galactic21** [comment]
Well im using the latest version, 1.4.0. It is installed when i install your API using https://rubygems.org/gems/influxdb-client and https://rubygems.org/gems/influxdb-client-apis. The problem is in the chef environment, there must be some dependency that is not being installed correctly but through the logs i cannot understand what is missing and I have 100% absolute sure that has to do with this Typhoeus library.

**Comment by bednar** [comment]
Minimal required version of `Typhoeus` library by `influxdb-client-apis` is `1.0.1`. You can try manually downgrade this library to another version.

**Comment by Galactic21** [comment]
I already tried that and it shouldn't be the problem because I already ran my script locally and everything is working with the operating system gems. The same gems and versions are being installed on the chef, but the "Segmention Fault" error persist.

**Comment by bednar** [comment]
This issue has been closed because it has not had recent activity. Please reopen if this issue is still important to you and you have additionally information.
