### ISSUE TITLE
 Update password using user API problems

### ISSUE THREAD

**Issue by Galactic21** [influxdata/influxdb-client-ruby#81]
Good afternoon, I am creating a user management from your user api and I am already able to add users and associate them with an organization. However, I noticed that when I create a user I don't have any field to specify the associated password. Then I saw the function "post_users_id_password ()" and from what I saw, 2 mandatory parameters are expected. My problem is in specifying the " password_reset_body ". From swagger.yml, I assume that this parameter is waiting for a string. I did that and gave me this error and I just wanted to ask if I'm doing something wrong or even interpreting something incorrectly.

Error:

![image](https://user-images.githubusercontent.com/32776046/117849592-5ebc0000-b27c-11eb-805e-95f9205d155c.png)

Code: 

![image](https://user-images.githubusercontent.com/32776046/117849898-ae023080-b27c-11eb-9f93-5db939589eef.png)

Cheers.

**Comment by bednar** [comment]
Hi @Galactic21,

pass your password via `hash`:

```ruby
api.create_users_api.post_users_id_password(user_ex.id, { password: password })
```

Regards

**Comment by Galactic21** [comment]
@bednar thank you.
