### ISSUE TITLE
PatchBucketRequest model implementation missing

### ISSUE THREAD

**Issue by prevosti** [influxdata/influxdb-client-ruby#98]
The implementation of the model `PatchBucketRequest` is missing though it is referenced in the BucketsApi class.

BucketsApi: https://github.com/influxdata/influxdb-client-ruby/blob/master/apis/lib/influxdb2/apis/generated/api/buckets_api.rb

PatchBucketRequest model should be here (similar to PatchOrganizationRequest), but it’s not: https://github.com/influxdata/influxdb-client-ruby/tree/master/apis/lib/influxdb2/apis/generated/models

**Comment by bednar** [comment]
Hi @prevosti,

thanks for using our client.

I will prepare a PR to fix this issue. As a workaround you can pass `PatchBucketRequest` as a `Hash`:

```ruby
updated = @client.create_buckets_api
                 .patch_buckets_id(bucket_id, patch_bucket_request = { "description" => "updated description" })
puts updated
```

Regards
